# Form implementation generated from reading ui file 'FreeWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.axis1Slider = QtWidgets.QSlider(parent=self.centralwidget)
        self.axis1Slider.setGeometry(QtCore.QRect(50, 280, 691, 18))
        self.axis1Slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.axis1Slider.setObjectName("axis1Slider")
        self.homeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.homeButton.setGeometry(QtCore.QRect(20, 10, 111, 24))
        self.homeButton.setObjectName("homeButton")
        self.minPos1Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.minPos1Label.setGeometry(QtCore.QRect(30, 300, 49, 16))
        self.minPos1Label.setObjectName("minPos1Label")
        self.maxPos1Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.maxPos1Label.setGeometry(QtCore.QRect(710, 300, 49, 16))
        self.maxPos1Label.setObjectName("maxPos1Label")
        self.pos1lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pos1lineEdit.setGeometry(QtCore.QRect(50, 250, 113, 21))
        self.pos1lineEdit.setObjectName("pos1lineEdit")
        self.setPos1Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.setPos1Button.setGeometry(QtCore.QRect(170, 250, 75, 24))
        self.setPos1Button.setObjectName("setPos1Button")
        self.maxPos2Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.maxPos2Label.setGeometry(QtCore.QRect(700, 440, 49, 16))
        self.maxPos2Label.setObjectName("maxPos2Label")
        self.axis2Slider = QtWidgets.QSlider(parent=self.centralwidget)
        self.axis2Slider.setGeometry(QtCore.QRect(40, 420, 691, 18))
        self.axis2Slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.axis2Slider.setObjectName("axis2Slider")
        self.minPos2Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.minPos2Label.setGeometry(QtCore.QRect(20, 440, 49, 16))
        self.minPos2Label.setObjectName("minPos2Label")
        self.pos2lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pos2lineEdit.setGeometry(QtCore.QRect(50, 390, 113, 21))
        self.pos2lineEdit.setObjectName("pos2lineEdit")
        self.setPos2Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.setPos2Button.setGeometry(QtCore.QRect(170, 390, 75, 24))
        self.setPos2Button.setObjectName("setPos2Button")
        self.stopButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(440, 70, 261, 151))
        self.stopButton.setObjectName("stopButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.homeButton.setText(_translate("MainWindow", "Back to Home"))
        self.minPos1Label.setText(_translate("MainWindow", "TextLabel"))
        self.maxPos1Label.setText(_translate("MainWindow", "TextLabel"))
        self.setPos1Button.setText(_translate("MainWindow", "Enter"))
        self.maxPos2Label.setText(_translate("MainWindow", "TextLabel"))
        self.minPos2Label.setText(_translate("MainWindow", "TextLabel"))
        self.setPos2Button.setText(_translate("MainWindow", "Enter"))
        self.stopButton.setText(_translate("MainWindow", "Stop all axes"))
